### ISSUE TITLE
You forgot to commit files

### ISSUE THREAD

**Issue by slopjong** [trevorpower/hackerspaces-status-wall#9]
Did you forget to commit something? Your code cannot work like this. 

Let me know if I missed something but I simply followed the readme which doesn't work as is.

This is the directory structure of the database module:

```
|-- database
|   |-- collections.coffee
|   |-- create.coffee
|   `-- README.md
```

You require database and production but they don't exist:

```
database = require('../database/database') require('../database/settings/production')

database.connect (err, db) ->
  if err
    console.log err
    process.exit()
  else
    require('../database/create') db, {}, (err) ->
      console.log err if err
      process.exit()
```

As you see here:

```
Error: Cannot find module '../database/database'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/tasks/create_database.coffee:4:14)
    at Object.<anonymous> (/vagrant/tasks/create_database.coffee:18:4)
    at Module._compile (module.js:456:26)
    at Object.exports.run (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:68:25)
    at compileScript (/usr/lib/coffee-script/lib/coffee-script/command.js:135:29)
    at /usr/lib/coffee-script/lib/coffee-script/command.js:110:18
```

**Comment by slopjong** [comment]
Here are the latest changes: [slopjong/hackerspaces-status-wall/feature/vagrant-box](https://github.com/slopjong/hackerspaces-status-wall/tree/feature/vagrant-box)

Here's how to work with vagrant: #8

**Comment by slopjong** [comment]
@raylton and I would like to get the local virtual machine run in order to contribute. @trevorpower, whenever your little boy/girl spends you some free time and you're not too stressed, we were very thankful if you clarified if something is missing or help us getting the db initialized correctly :-)

We won't push anything to the master branch until we can guarantee that our changes are working as expected so that the website never will break ;-)

**Comment by slopjong** [comment]
@trevorpower can you give me an explanation for the missing module?

**Comment by dbrgn** [comment]
I also tried to get this working again by [creating a Dockerfile](https://github.com/coredump-ch/hackerspaces-status-wall/tree/docker). But I'm facing the same issue.

@trevorpower if you can give us enough information to get a local configuration working, we can start to contribute.

@slopjong did you have any success in getting this to run?
